// Демо-аккаунты для тестирования

export const DEMO_ACCOUNTS = {
  // Салон красоты
  beauty: {
    name: 'Салон красоты "Красотка"',
    type: 'beauty',
    stats: {
      bookingsToday: 8,
      newClients: 3,
      revenueToday: 12500,
      averageCheck: 1562,
    },
    services: [
      {
        id: 1,
        name: 'Стрижка женская',
        category: 'Стрижки',
        price: 1500,
        duration: 90,
        staff: ['Мария Петрова', 'Анна Сидорова'],
        bookings: 45,
        isActive: true,
        image: null,
        description: 'Модельная стрижка с укладкой',
      },
      {
        id: 2,
        name: 'Стрижка мужская',
        category: 'Стрижки',
        price: 800,
        duration: 45,
        staff: ['Иван Иванов'],
        bookings: 67,
        isActive: true,
        image: null,
        description: 'Классическая мужская стрижка',
      },
      {
        id: 3,
        name: 'Окрашивание',
        category: 'Окрашивание',
        price: 3000,
        duration: 120,
        staff: ['Мария Петрова'],
        bookings: 23,
        isActive: true,
        image: null,
        description: 'Окрашивание волос премиум красителями',
      },
      {
        id: 4,
        name: 'Маникюр',
        category: 'Ногтевой сервис',
        price: 1200,
        duration: 60,
        staff: ['Елена Козлова'],
        bookings: 89,
        isActive: true,
        image: null,
        description: 'Классический маникюр с покрытием',
      },
      {
        id: 5,
        name: 'Педикюр',
        category: 'Ногтевой сервис',
        price: 1500,
        duration: 75,
        staff: ['Елена Козлова'],
        bookings: 56,
        isActive: true,
        image: null,
        description: 'Аппаратный педикюр',
      },
    ],
    staff: [
      {
        id: 1,
        name: 'Мария Петрова',
        position: 'Старший мастер',
        phone: '+7 (999) 111-22-33',
        email: 'maria@example.com',
        avatar: null,
        rating: 4.9,
        bookings: 156,
        revenue: 234000,
        isActive: true,
        services: ['Стрижка женская', 'Окрашивание', 'Укладка'],
        workingHours: 'Пн-Пт: 10:00-19:00',
      },
      {
        id: 2,
        name: 'Иван Иванов',
        position: 'Барбер',
        phone: '+7 (999) 222-33-44',
        email: 'ivan@example.com',
        avatar: null,
        rating: 4.8,
        bookings: 189,
        revenue: 151200,
        isActive: true,
        services: ['Стрижка мужская', 'Бритье', 'Уход за бородой'],
        workingHours: 'Вт-Сб: 11:00-20:00',
      },
      {
        id: 3,
        name: 'Елена Козлова',
        position: 'Мастер маникюра',
        phone: '+7 (999) 333-44-55',
        email: 'elena@example.com',
        avatar: null,
        rating: 5.0,
        bookings: 203,
        revenue: 243600,
        isActive: true,
        services: ['Маникюр', 'Педикюр', 'Наращивание'],
        workingHours: 'Пн-Сб: 9:00-18:00',
      },
    ],
    clients: [
      {
        id: 1,
        name: 'Анна Иванова',
        phone: '+7 (999) 123-45-67',
        email: 'anna@example.com',
        avatar: null,
        totalBookings: 12,
        totalSpent: 18000,
        lastVisit: '2024-11-20',
        rating: 5,
        tags: ['VIP', 'Постоянный'],
      },
      {
        id: 2,
        name: 'Дмитрий Смирнов',
        phone: '+7 (999) 234-56-78',
        email: 'dmitry@example.com',
        avatar: null,
        totalBookings: 5,
        totalSpent: 10000,
        lastVisit: '2024-11-18',
        rating: 4,
        tags: ['Постоянный'],
      },
      {
        id: 3,
        name: 'Елена Козлова',
        phone: '+7 (999) 345-67-89',
        email: 'elena@example.com',
        avatar: null,
        totalBookings: 1,
        totalSpent: 3000,
        lastVisit: '2024-11-15',
        rating: 5,
        tags: ['Новый'],
      },
      {
        id: 4,
        name: 'Сергей Петров',
        phone: '+7 (999) 456-78-90',
        email: 'sergey@example.com',
        avatar: null,
        totalBookings: 8,
        totalSpent: 12000,
        lastVisit: '2024-11-19',
        rating: 5,
        tags: ['VIP'],
      },
    ],
    bookings: [
      {
        id: 1,
        client: 'Анна Иванова',
        phone: '+7 (999) 123-45-67',
        service: 'Стрижка женская',
        staff: 'Мария Петрова',
        date: '2024-11-25',
        time: '14:00',
        duration: 90,
        price: 1500,
        status: 'confirmed',
        avatar: null,
      },
      {
        id: 2,
        client: 'Дмитрий Смирнов',
        phone: '+7 (999) 234-56-78',
        service: 'Стрижка мужская',
        staff: 'Иван Иванов',
        date: '2024-11-25',
        time: '15:30',
        duration: 60,
        price: 800,
        status: 'pending',
        avatar: null,
      },
      {
        id: 3,
        client: 'Елена Козлова',
        phone: '+7 (999) 345-67-89',
        service: 'Окрашивание',
        staff: 'Мария Петрова',
        date: '2024-11-25',
        time: '17:00',
        duration: 120,
        price: 3000,
        status: 'confirmed',
        avatar: null,
      },
    ],
    analytics: {
      revenue: 125000,
      bookings: 48,
      newClients: 32,
      rating: 4.8,
      reviewCount: 156,
      topServices: [
        { name: 'Стрижка женская', bookings: 156, revenue: 234000 },
        { name: 'Маникюр', bookings: 203, revenue: 243600 },
        { name: 'Стрижка мужская', bookings: 189, revenue: 151200 },
      ],
      topStaff: [
        { name: 'Елена Козлова', bookings: 203, rating: 5.0 },
        { name: 'Иван Иванов', bookings: 189, rating: 4.8 },
        { name: 'Мария Петрова', bookings: 156, rating: 4.9 },
      ],
      revenueData: [15000, 18000, 22000, 19000, 25000, 16000, 10000],
      bookingsData: [5, 7, 9, 8, 12, 6, 4],
    },
  },

  // Фитнес-центр
  fitness: {
    name: 'Фитнес-центр "Энергия"',
    type: 'fitness',
    stats: {
      bookingsToday: 15,
      newClients: 5,
      revenueToday: 18500,
      averageCheck: 1233,
    },
    services: [
      {
        id: 1,
        name: 'Персональная тренировка',
        category: 'Тренировки',
        price: 2000,
        duration: 60,
        staff: ['Алексей Фитнесов', 'Ольга Спортивная'],
        bookings: 78,
        isActive: true,
        image: null,
        description: 'Индивидуальная тренировка с тренером',
      },
      {
        id: 2,
        name: 'Групповая тренировка',
        category: 'Тренировки',
        price: 800,
        duration: 60,
        staff: ['Ольга Спортивная', 'Игорь Силовой'],
        bookings: 145,
        isActive: true,
        image: null,
        description: 'Групповое занятие до 15 человек',
      },
      {
        id: 3,
        name: 'Йога',
        category: 'Йога и растяжка',
        price: 1000,
        duration: 90,
        staff: ['Анна Йогина'],
        bookings: 92,
        isActive: true,
        image: null,
        description: 'Хатха-йога для всех уровней',
      },
      {
        id: 4,
        name: 'Массаж спортивный',
        category: 'Массаж',
        price: 2500,
        duration: 60,
        staff: ['Михаил Массажист'],
        bookings: 56,
        isActive: true,
        image: null,
        description: 'Восстановительный массаж после тренировок',
      },
      {
        id: 5,
        name: 'Консультация диетолога',
        category: 'Консультации',
        price: 1500,
        duration: 45,
        staff: ['Елена Диетолог'],
        bookings: 34,
        isActive: true,
        image: null,
        description: 'Составление индивидуального плана питания',
      },
    ],
    staff: [
      {
        id: 1,
        name: 'Алексей Фитнесов',
        position: 'Старший тренер',
        phone: '+7 (999) 777-88-99',
        email: 'alex@fitness.com',
        avatar: null,
        rating: 4.9,
        bookings: 234,
        revenue: 468000,
        isActive: true,
        services: ['Персональная тренировка', 'Функциональный тренинг'],
        workingHours: 'Пн-Пт: 8:00-20:00',
      },
      {
        id: 2,
        name: 'Ольга Спортивная',
        position: 'Тренер групповых программ',
        phone: '+7 (999) 888-99-00',
        email: 'olga@fitness.com',
        avatar: null,
        rating: 4.8,
        bookings: 312,
        revenue: 249600,
        isActive: true,
        services: ['Групповая тренировка', 'Персональная тренировка'],
        workingHours: 'Пн-Сб: 9:00-21:00',
      },
      {
        id: 3,
        name: 'Анна Йогина',
        position: 'Инструктор йоги',
        phone: '+7 (999) 999-00-11',
        email: 'anna@fitness.com',
        avatar: null,
        rating: 5.0,
        bookings: 187,
        revenue: 187000,
        isActive: true,
        services: ['Йога', 'Растяжка', 'Медитация'],
        workingHours: 'Вт-Вс: 10:00-19:00',
      },
      {
        id: 4,
        name: 'Михаил Массажист',
        position: 'Массажист',
        phone: '+7 (999) 000-11-22',
        email: 'mikhail@fitness.com',
        avatar: null,
        rating: 4.9,
        bookings: 156,
        revenue: 390000,
        isActive: true,
        services: ['Массаж спортивный', 'Массаж расслабляющий'],
        workingHours: 'Ср-Вс: 11:00-20:00',
      },
    ],
    clients: [
      {
        id: 1,
        name: 'Петр Здоровый',
        phone: '+7 (999) 111-00-99',
        email: 'petr@example.com',
        avatar: null,
        totalBookings: 24,
        totalSpent: 48000,
        lastVisit: '2024-11-21',
        rating: 5,
        tags: ['VIP', 'Постоянный'],
      },
      {
        id: 2,
        name: 'Мария Активная',
        phone: '+7 (999) 222-11-00',
        email: 'maria@example.com',
        avatar: null,
        totalBookings: 18,
        totalSpent: 36000,
        lastVisit: '2024-11-20',
        rating: 5,
        tags: ['Постоянный'],
      },
      {
        id: 3,
        name: 'Игорь Новичок',
        phone: '+7 (999) 333-22-11',
        email: 'igor@example.com',
        avatar: null,
        totalBookings: 2,
        totalSpent: 4000,
        lastVisit: '2024-11-19',
        rating: 4,
        tags: ['Новый'],
      },
      {
        id: 4,
        name: 'Светлана Фитнес',
        phone: '+7 (999) 444-33-22',
        email: 'svetlana@example.com',
        avatar: null,
        totalBookings: 15,
        totalSpent: 30000,
        lastVisit: '2024-11-21',
        rating: 5,
        tags: ['VIP'],
      },
      {
        id: 5,
        name: 'Андрей Силовой',
        phone: '+7 (999) 555-44-33',
        email: 'andrey@example.com',
        avatar: null,
        totalBookings: 10,
        totalSpent: 20000,
        lastVisit: '2024-11-18',
        rating: 5,
        tags: ['Постоянный'],
      },
    ],
    bookings: [
      {
        id: 1,
        client: 'Петр Здоровый',
        phone: '+7 (999) 111-00-99',
        service: 'Персональная тренировка',
        staff: 'Алексей Фитнесов',
        date: '2024-11-25',
        time: '10:00',
        duration: 60,
        price: 2000,
        status: 'confirmed',
        avatar: null,
      },
      {
        id: 2,
        client: 'Мария Активная',
        phone: '+7 (999) 222-11-00',
        service: 'Йога',
        staff: 'Анна Йогина',
        date: '2024-11-25',
        time: '11:00',
        duration: 90,
        price: 1000,
        status: 'confirmed',
        avatar: null,
      },
      {
        id: 3,
        client: 'Игорь Новичок',
        phone: '+7 (999) 333-22-11',
        service: 'Групповая тренировка',
        staff: 'Ольга Спортивная',
        date: '2024-11-25',
        time: '18:00',
        duration: 60,
        price: 800,
        status: 'pending',
        avatar: null,
      },
      {
        id: 4,
        client: 'Светлана Фитнес',
        phone: '+7 (999) 444-33-22',
        service: 'Массаж спортивный',
        staff: 'Михаил Массажист',
        date: '2024-11-26',
        time: '14:00',
        duration: 60,
        price: 2500,
        status: 'confirmed',
        avatar: null,
      },
      {
        id: 5,
        client: 'Андрей Силовой',
        phone: '+7 (999) 555-44-33',
        service: 'Персональная тренировка',
        staff: 'Алексей Фитнесов',
        date: '2024-11-26',
        time: '16:00',
        duration: 60,
        price: 2000,
        status: 'confirmed',
        avatar: null,
      },
    ],
    analytics: {
      revenue: 185000,
      bookings: 67,
      newClients: 45,
      rating: 4.9,
      reviewCount: 234,
      topServices: [
        { name: 'Групповая тренировка', bookings: 145, revenue: 116000 },
        { name: 'Йога', bookings: 92, revenue: 92000 },
        { name: 'Персональная тренировка', bookings: 78, revenue: 156000 },
      ],
      topStaff: [
        { name: 'Ольга Спортивная', bookings: 312, rating: 4.8 },
        { name: 'Алексей Фитнесов', bookings: 234, rating: 4.9 },
        { name: 'Анна Йогина', bookings: 187, rating: 5.0 },
      ],
      revenueData: [22000, 25000, 28000, 24000, 30000, 26000, 18000],
      bookingsData: [8, 10, 12, 9, 14, 10, 7],
    },
  },
};

export type DemoAccountType = keyof typeof DEMO_ACCOUNTS;

export function getDemoAccount(type: DemoAccountType) {
  return DEMO_ACCOUNTS[type];
}
